/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.FornecedoresBeans;
import Beans.BancosBeans;
import Beans.ListSegFornecedores;
import DAO.Diversas;
import DAO.FornecedoresDAO;
import static GUI.Principal.listBancos;
import Utilitarios.CentralizarTabela;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;


public class frmCadFornecedores extends javax.swing.JInternalFrame {

public DefaultTableModel TbForn;
Diversas DiversasD;
private MaskFormatter CNPJMask;
private MaskFormatter CPFMask;
List<ListSegFornecedores> listSegmentos;
FornecedoresDAO FornecedoresD;
FornecedoresBeans FornB;

    public frmCadFornecedores() {
        initComponents();
        DiversasD = new Diversas();
        FornecedoresD  = new FornecedoresDAO();
        FornB = new FornecedoresBeans();
        getTabelaFornecedores();
        carregarSegmentos();
        carregarBancos();
        maskFormaterCPF();
    }
    
    private JTable getTabelaFornecedores(){
            if(TbForn == null){
                TbForn = (DefaultTableModel) tb_fornecedores.getModel();
            }
            ((DefaultTableCellRenderer) tb_fornecedores.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
            CentralizarTabela centralizar = new CentralizarTabela();
            centralizar.centralizarTabela(tb_fornecedores);
            
        return tb_fornecedores;
    }
    
    private void carregarBancos() {
        if (listBancos == null) {
            listBancos = new ArrayList<>();
            listBancos = DiversasD.ListBancos();
        }
        cb_banco.addItem("-");
        for (BancosBeans list : listBancos) {
            cb_banco.addItem(list);
        }
    }
    
    private void maskFormaterCPF(){
         try {
            CNPJMask = new MaskFormatter("##.###.###/####-##");
            CPFMask = new MaskFormatter("###.###.###-##");
         } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
    
    private void carregarSegmentos() {
        if (listSegmentos == null) {
            listSegmentos = new ArrayList<>();
            listSegmentos = FornecedoresD.SegmentoFornecedor();
        }
        cb_segmento.addItem("-");
        for (ListSegFornecedores list : listSegmentos) {
            cb_segmento.addItem(list);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nomeFantasia = new javax.swing.JTextField();
        txt_razaoSocial = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        cb_segmento = new javax.swing.JComboBox<>();
        cb_tipoPessoa = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        cb_banco = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        txt_agencia = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        txt_conta = new javax.swing.JTextField();
        txt_cnpj = new javax.swing.JFormattedTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        btn_pesquisarCompra = new javax.swing.JButton();
        btn_novo1 = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tb_fornecedores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedores");

        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane();
        scroll.add(jPanel2);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome Fantasia");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Razão Social");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Telefone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Segmento");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cadastro");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.setEnabled(false);

        txt_telefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefone.setEnabled(false);

        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_email.setEnabled(false);

        cb_segmento.setEnabled(false);

        cb_tipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "CPF", "CNPJ" }));
        cb_tipoPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoPessoaItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Banco");

        cb_banco.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Ag.");

        txt_agencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_agencia.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("C.C");

        txt_conta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_conta.setEnabled(false);

        txt_cnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_razaoSocial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_agencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_segmento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txt_nomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(txt_razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_segmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_tipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_pesquisarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/buscar pequeno.png"))); // NOI18N
        btn_pesquisarCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_pesquisarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarCompraActionPerformed(evt);
            }
        });

        btn_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir-32.png"))); // NOI18N
        btn_novo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_novo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo1ActionPerformed(evt);
            }
        });

        btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar_32_32.png"))); // NOI18N
        btn_Salvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/editar_32_32.png"))); // NOI18N
        btn_editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/deletar_32_32.png"))); // NOI18N
        btn_excluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tb_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Fantasia", "Razão Social", "Telefone", "E-mail", "Segmento", "Tipo Cadastro", "CPF / CNPJ", "Banco", "Agência", "Conta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_fornecedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_fornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_fornecedores);
        if (tb_fornecedores.getColumnModel().getColumnCount() > 0) {
            tb_fornecedores.getColumnModel().getColumn(0).setResizable(false);
            tb_fornecedores.getColumnModel().getColumn(0).setPreferredWidth(60);
            tb_fornecedores.getColumnModel().getColumn(1).setMinWidth(120);
            tb_fornecedores.getColumnModel().getColumn(1).setPreferredWidth(120);
            tb_fornecedores.getColumnModel().getColumn(1).setMaxWidth(200);
            tb_fornecedores.getColumnModel().getColumn(2).setMinWidth(120);
            tb_fornecedores.getColumnModel().getColumn(2).setPreferredWidth(120);
            tb_fornecedores.getColumnModel().getColumn(2).setMaxWidth(200);
            tb_fornecedores.getColumnModel().getColumn(3).setMinWidth(90);
            tb_fornecedores.getColumnModel().getColumn(3).setPreferredWidth(90);
            tb_fornecedores.getColumnModel().getColumn(3).setMaxWidth(110);
            tb_fornecedores.getColumnModel().getColumn(4).setMinWidth(90);
            tb_fornecedores.getColumnModel().getColumn(4).setPreferredWidth(90);
            tb_fornecedores.getColumnModel().getColumn(4).setMaxWidth(110);
            tb_fornecedores.getColumnModel().getColumn(5).setMinWidth(110);
            tb_fornecedores.getColumnModel().getColumn(5).setPreferredWidth(110);
            tb_fornecedores.getColumnModel().getColumn(5).setMaxWidth(130);
            tb_fornecedores.getColumnModel().getColumn(6).setMinWidth(70);
            tb_fornecedores.getColumnModel().getColumn(6).setPreferredWidth(70);
            tb_fornecedores.getColumnModel().getColumn(6).setMaxWidth(70);
            tb_fornecedores.getColumnModel().getColumn(7).setMinWidth(120);
            tb_fornecedores.getColumnModel().getColumn(7).setPreferredWidth(120);
            tb_fornecedores.getColumnModel().getColumn(7).setMaxWidth(150);
            tb_fornecedores.getColumnModel().getColumn(8).setMinWidth(90);
            tb_fornecedores.getColumnModel().getColumn(8).setPreferredWidth(90);
            tb_fornecedores.getColumnModel().getColumn(8).setMaxWidth(110);
            tb_fornecedores.getColumnModel().getColumn(9).setMinWidth(80);
            tb_fornecedores.getColumnModel().getColumn(9).setPreferredWidth(80);
            tb_fornecedores.getColumnModel().getColumn(9).setMaxWidth(100);
            tb_fornecedores.getColumnModel().getColumn(10).setMinWidth(80);
            tb_fornecedores.getColumnModel().getColumn(10).setPreferredWidth(80);
            tb_fornecedores.getColumnModel().getColumn(10).setMaxWidth(110);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo1ActionPerformed
        habilitarCampos();
        btn_Salvar.setEnabled(true);
        btn_excluir.setEnabled(false);
        btn_editar.setEnabled(false);
        
    }//GEN-LAST:event_btn_novo1ActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        int cadastrar = JOptionPane.showConfirmDialog(null, "Deseja Cadastrar este Fornecedor?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (cadastrar == JOptionPane.YES_OPTION) {
            popularBeans();
            FornecedoresD.cadastrarFornecedor(FornB);
            limparCampos();
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int excluir = JOptionPane.showConfirmDialog(null, "Deseja EXCLUIR esta Compra de Gado, os dados serão apagados permanentemente?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (excluir == JOptionPane.YES_OPTION) {

        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int editar = JOptionPane.showConfirmDialog(null, "Deseja editar este fornecedor?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (editar == JOptionPane.YES_OPTION) {
            FornB.setID(Integer.parseInt(txt_id.getText()));
            popularBeans();
            FornecedoresD.editarFornecedor(FornB);
            limparCampos();       
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void cb_tipoPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoPessoaItemStateChanged
         if (cb_tipoPessoa.getSelectedItem().toString().equals("CPF")){
            txt_cnpj.setValue(null);
            txt_cnpj.setFormatterFactory(new DefaultFormatterFactory(CPFMask));     
         } else if(cb_tipoPessoa.getSelectedItem().toString().equals("CNPJ")){
            txt_cnpj.setValue(null);
            txt_cnpj.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));
         } else if(cb_tipoPessoa.getSelectedItem().toString().equals("-")){
            txt_cnpj.setValue(null);
            txt_cnpj.setFormatterFactory(null);
        }
    }//GEN-LAST:event_cb_tipoPessoaItemStateChanged

    private void btn_pesquisarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarCompraActionPerformed
        popularBeansPesquisa();
        FornecedoresD.buscarFornecedores(FornB, TbForn);
    }//GEN-LAST:event_btn_pesquisarCompraActionPerformed

    private void tb_fornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_fornecedoresMouseClicked
        preencherCampos();
        if (evt.getClickCount() == 2) {
                habilitarCampos();
                btn_editar.setEnabled(true);
        } else {
            desabilitarCampos();
            btn_Salvar.setEnabled(true);
            btn_editar.setEnabled(true);
        } 
    }//GEN-LAST:event_tb_fornecedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Salvar;
    public javax.swing.JButton btn_editar;
    public javax.swing.JButton btn_excluir;
    public javax.swing.JButton btn_novo1;
    public javax.swing.JButton btn_pesquisarCompra;
    javax.swing.JComboBox<Object> cb_banco;
    javax.swing.JComboBox<Object> cb_segmento;
    javax.swing.JComboBox<String> cb_tipoPessoa;
    public javax.swing.JTable tb_fornecedores;
    javax.swing.JTextField txt_agencia;
    javax.swing.JFormattedTextField txt_cnpj;
    javax.swing.JTextField txt_conta;
    javax.swing.JTextField txt_email;
    javax.swing.JTextField txt_id;
    javax.swing.JTextField txt_nomeFantasia;
    javax.swing.JTextField txt_razaoSocial;
    javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    private void popularBeans(){
        FornB.setIdSegmento(getIdSegmento());
        FornB.setNomeFantasia(txt_nomeFantasia.getText());
        FornB.setRazaoSocial(txt_razaoSocial.getText());
        FornB.setTelefone(txt_telefone.getText());
        FornB.setEmail(txt_email.getText());
        FornB.setTipoPessoa(cb_tipoPessoa.getSelectedItem().toString());
        FornB.setCnpj(txt_cnpj.getText());
        FornB.setBanco(cb_banco.getSelectedItem().toString());
        FornB.setAgencia(txt_agencia.getText());
        FornB.setConta(txt_conta.getText());
    }

    private void popularBeansPesquisa(){   
        FornB.setNomeFantasia(txt_nomeFantasia.getText());
        FornB.setRazaoSocial(txt_razaoSocial.getText());
        if (cb_tipoPessoa.getSelectedItem().equals("-")){
            FornB.setCnpj("");
        } else {
            FornB.setCnpj(txt_cnpj.getText());
        }
    }

    private int getIdSegmento(){
        if (cb_segmento.getSelectedIndex() == 0){
            return 0;
        } else {
            int index = cb_segmento.getSelectedIndex()-1;
            return listSegmentos.get(index).getId_segmento();
        }
    }

    private void preencherCampos(){
        int i = tb_fornecedores.getSelectedRow();
        txt_id.setText((TbForn.getValueAt(i, 0) == null ? "" : TbForn.getValueAt(i, 0).toString()));
        txt_nomeFantasia.setText((TbForn.getValueAt(i, 1) == null ? "" : TbForn.getValueAt(i, 1).toString()));
        txt_razaoSocial.setText((TbForn.getValueAt(i, 2) == null ? "" : TbForn.getValueAt(i, 2).toString()));
        txt_telefone.setText((TbForn.getValueAt(i, 3) == null ? "" : TbForn.getValueAt(i, 3).toString()));
        txt_email.setText((TbForn.getValueAt(i, 4) == null ? "" : TbForn.getValueAt(i, 4).toString()));
        
        cb_segmento.setSelectedIndex(setSelectedSegmento(i));
        
        cb_tipoPessoa.setSelectedItem((TbForn.getValueAt(i, 6) == null ? "" : TbForn.getValueAt(i, 6).toString()));
        txt_cnpj.setText((TbForn.getValueAt(i, 7) == null ? "" : TbForn.getValueAt(i, 7).toString()));
        cb_banco.setSelectedItem((TbForn.getValueAt(i, 8) == null ? "-" : TbForn.getValueAt(i, 8).toString()));
        txt_agencia.setText((TbForn.getValueAt(i, 9) == null ? "" : TbForn.getValueAt(i, 9).toString()));
        txt_conta.setText((TbForn.getValueAt(i, 10) == null ? "" : TbForn.getValueAt(i, 10).toString()));
    }

    private void habilitarCampos(){
            txt_nomeFantasia.setEnabled(true);
            txt_razaoSocial.setEnabled(true);
            txt_telefone.setEnabled(true);
            txt_email.setEnabled(true);
            cb_segmento.setEnabled(true);
            cb_tipoPessoa.setEnabled(true);
            txt_cnpj.setEnabled(true);
            cb_banco.setEnabled(true);
            txt_agencia.setEnabled(true);
            txt_conta.setEnabled(true);
    }

    private void desabilitarCampos(){
            txt_nomeFantasia.setEnabled(false);
            txt_razaoSocial.setEnabled(false);
            txt_telefone.setEnabled(false);
            txt_email.setEnabled(false);
            cb_segmento.setEnabled(false);
            cb_tipoPessoa.setEnabled(false);
            txt_cnpj.setEnabled(false);
            cb_banco.setEnabled(false);
            txt_agencia.setEnabled(false);
            txt_conta.setEnabled(false);
    }

    public void limparCampos(){
        txt_id.setText("");
        txt_nomeFantasia.setText("");
        txt_razaoSocial.setText("");
        txt_telefone.setText("");
        txt_email.setText("");
        cb_tipoPessoa.setSelectedItem("-");
        cb_segmento.setSelectedItem("-");
        txt_cnpj.setText("");
        cb_banco.setSelectedItem("-");
        txt_agencia.setText("");
        txt_conta.setText("");
    }

    private int setSelectedSegmento(Integer i){
        int index = 0;
        for (int j = 0; j < listSegmentos.size(); j++){
            if (listSegmentos.get(j).getId_segmento() == Integer.parseInt(TbForn.getValueAt(i,5).toString())){
                index = j+1;
                return index;
            }
        }
        return index ;
    }


}
