/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.ContaBancariaBeans;
import DAO.Diversas;
import static GUI.Principal.listContaOrigem;
import static GUI.frmLogin.dataAtual;
import Icones.FormatarICO;
import Utilitarios.Conexao;
import com.toedter.calendar.JDateChooser;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class frmGerarExtrato_CC extends javax.swing.JDialog {

    Diversas DiversasD;

    public frmGerarExtrato_CC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        DiversasD = new Diversas();
        carregarContasOrigem();
        txt_dtFinalPrevisao.setDate(getDataAtual());

    }

    private void carregarContasOrigem() {
        if (listContaOrigem == null) {
            listContaOrigem = new ArrayList<>();
            listContaOrigem = DiversasD.listContaOrigem();
        }
        ContaBancariaBeans l = new ContaBancariaBeans();
        l.setIdConta(0);
        l.setDescricao("-");
        cb_contaExtrato.addItem(l);

        for (ContaBancariaBeans list : listContaOrigem) {
            cb_contaExtrato.addItem(list);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_dtInicialPrevisao =  new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        txt_dtFinalPrevisao =  new JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        btn_gerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cb_contaExtrato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_ordem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Previsão de Pagamentos");
        setModal(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Data Inicial");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Final");

        btn_gerar.setText("Gerar Relatório");
        btn_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Conta Corrente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ordenar por:");

        cb_ordem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data", "Favorecido", "Nº Documento" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_dtInicialPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dtFinalPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_contaExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_ordem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_gerar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txt_dtInicialPrevisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dtFinalPrevisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cb_contaExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cb_ordem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btn_gerar)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerarActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar o Extrato da Conta" + cb_contaExtrato.getSelectedItem().toString() + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        Conexao.ReiniciarCon();
        if (confirma == JOptionPane.YES_OPTION) {
            Map p = new HashMap();
            JasperReport relatorio;
            JasperPrint impressao;
            JasperViewer jrviewer = null;
            try {
                if (!txt_dtInicialPrevisao.getDate().equals("")) {
                    p.put("dtInicial", txt_dtInicialPrevisao.getDate());
                    p.put("dtFinal", txt_dtFinalPrevisao.getDate());
                    p.put("idConta", getIDContaOrigem(cb_contaExtrato));
                    p.put("contaBancaria", cb_contaExtrato.getSelectedItem().toString());
                    p.put("caminhoLogo", FormatarICO.logoTipo().getImage());
                    p.put("Ordem", getOrderBy());
                    relatorio = JasperCompileManager.compileReport(new File("").getClass().getResourceAsStream("/Relatorios/Extrato_CC.jrxml"));
                    impressao = JasperFillManager.fillReport(relatorio, p, Conexao.getConnection());
                    jrviewer = new JasperViewer(impressao, false);
                    jrviewer.setVisible(true);
                    jrviewer.toFront();
                } else {
                    JOptionPane.showMessageDialog(null, "Verifique o intervalo de datas!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            this.dispose();
            jrviewer.toFront();
        }
    }//GEN-LAST:event_btn_gerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGerarExtrato_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGerarExtrato_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGerarExtrato_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGerarExtrato_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmGerarExtrato_CC dialog = new frmGerarExtrato_CC(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gerar;
    private javax.swing.JComboBox<ContaBancariaBeans> cb_contaExtrato;
    private javax.swing.JComboBox<String> cb_ordem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser txt_dtFinalPrevisao;
    private com.toedter.calendar.JDateChooser txt_dtInicialPrevisao;
    // End of variables declaration//GEN-END:variables

    private Integer getIDContaOrigem(JComboBox comboBox) {
        if (comboBox.getSelectedIndex() != 0) {
            return listContaOrigem.get(comboBox.getSelectedIndex() - 1).getIdConta();
        }
        return 0;
    }

    private Date getDataAtual() {
        Date d = new Date(System.currentTimeMillis());
        Calendar c = Calendar.getInstance();
        //c.add(Calendar.DAY_OF_WEEK, 0);
        d = c.getTime();
        return d;
    }

    private String getOrderBy(){
        String s = cb_ordem.getSelectedItem().toString();
        if (s.equals("Data")){
            return "dataMov";
        } else if (s.equals("Favorecido")){
            return "Nome";
        } else if (s.equals("Nº Documento")){
            return "nDocPagto";
        } else if (s.equals("")){
            return "";
        }
        return "dataMov";
    }
    
}
