/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Diversas;
import Icones.FormatarICO;
import Utilitarios.Conexao;
import Utilitarios.Corretores;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import GUI.frmSaidaGado;

/**
 *
 * @author Bruno
 */
public class frmPesquisarEscala extends javax.swing.JDialog {

    Diversas DiversasD;
    DefaultTableModel TbEscalas;
    private String Origem;
    private String Destino;
    frmSaidaGado frmSaida;
    public static String pesquisarNescala;
    
    public frmPesquisarEscala(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        frmSaida = new frmSaidaGado();
        
        DiversasD = new Diversas();
        TbEscalas = (DefaultTableModel)tb_escalas.getModel();
        
        cb_Origem.setModel(new DefaultComboBoxModel( new Vector(DiversasD.pmfazenda())));
        cb_Destino.setModel(new DefaultComboBoxModel(new Vector(DiversasD.buscarFrigorifico())));
    
        txt_dtInicial.setDate(Corretores.PrimeiroDiaMes());
        txt_dtFinal.setDate(Corretores.UltimoDiaMes());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        txt_dtInicial = new com.toedter.calendar.JDateChooser();
        txt_dtFinal = new com.toedter.calendar.JDateChooser();
        cb_Origem = new javax.swing.JComboBox<>();
        cb_Destino = new javax.swing.JComboBox<>();
        btn_pesquisarCompra = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tb_escalas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Esacala de Abate");
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pesquisar"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Data Inicial");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Final");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Origem");

        btn_pesquisarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/buscar pequeno.png"))); // NOI18N
        btn_pesquisarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Origem, 0, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cb_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_Origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dtInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tb_escalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Venda", "Nº Escala", "Origem", "Data Embarque", "Categoria", "Destino", "Q. Venda", "Q. NF", "Q.GTA", "Q. Min", "Peso Total", "Peso Médio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_escalas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_escalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_escalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_escalas);
        if (tb_escalas.getColumnModel().getColumnCount() > 0) {
            tb_escalas.getColumnModel().getColumn(0).setResizable(false);
            tb_escalas.getColumnModel().getColumn(0).setPreferredWidth(0);
            tb_escalas.getColumnModel().getColumn(1).setMinWidth(70);
            tb_escalas.getColumnModel().getColumn(1).setPreferredWidth(70);
            tb_escalas.getColumnModel().getColumn(1).setMaxWidth(90);
            tb_escalas.getColumnModel().getColumn(2).setMinWidth(90);
            tb_escalas.getColumnModel().getColumn(2).setPreferredWidth(90);
            tb_escalas.getColumnModel().getColumn(2).setMaxWidth(150);
            tb_escalas.getColumnModel().getColumn(3).setMinWidth(100);
            tb_escalas.getColumnModel().getColumn(3).setPreferredWidth(100);
            tb_escalas.getColumnModel().getColumn(3).setMaxWidth(110);
            tb_escalas.getColumnModel().getColumn(4).setMinWidth(80);
            tb_escalas.getColumnModel().getColumn(4).setPreferredWidth(80);
            tb_escalas.getColumnModel().getColumn(4).setMaxWidth(100);
            tb_escalas.getColumnModel().getColumn(5).setMinWidth(80);
            tb_escalas.getColumnModel().getColumn(5).setPreferredWidth(80);
            tb_escalas.getColumnModel().getColumn(5).setMaxWidth(100);
            tb_escalas.getColumnModel().getColumn(6).setMinWidth(60);
            tb_escalas.getColumnModel().getColumn(6).setPreferredWidth(60);
            tb_escalas.getColumnModel().getColumn(6).setMaxWidth(60);
            tb_escalas.getColumnModel().getColumn(7).setMinWidth(60);
            tb_escalas.getColumnModel().getColumn(7).setPreferredWidth(60);
            tb_escalas.getColumnModel().getColumn(7).setMaxWidth(60);
            tb_escalas.getColumnModel().getColumn(8).setMinWidth(60);
            tb_escalas.getColumnModel().getColumn(8).setPreferredWidth(60);
            tb_escalas.getColumnModel().getColumn(8).setMaxWidth(60);
            tb_escalas.getColumnModel().getColumn(9).setMinWidth(60);
            tb_escalas.getColumnModel().getColumn(9).setPreferredWidth(60);
            tb_escalas.getColumnModel().getColumn(9).setMaxWidth(60);
            tb_escalas.getColumnModel().getColumn(10).setMinWidth(90);
            tb_escalas.getColumnModel().getColumn(10).setPreferredWidth(90);
            tb_escalas.getColumnModel().getColumn(10).setMaxWidth(120);
            tb_escalas.getColumnModel().getColumn(11).setMinWidth(90);
            tb_escalas.getColumnModel().getColumn(11).setPreferredWidth(90);
            tb_escalas.getColumnModel().getColumn(11).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 868, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarCompraActionPerformed
        if (cb_Origem.getSelectedItem().equals("-")){
            Origem = "";
        } else {
            Origem = cb_Origem.getSelectedItem().toString();
        }
        if (cb_Destino.getSelectedItem().equals("-")){
            Destino = "";
        } else {
            Destino = cb_Destino.getSelectedItem().toString();
        }   
        buscarEscalas();
    }//GEN-LAST:event_btn_pesquisarCompraActionPerformed

    private void tb_escalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_escalasMouseClicked
        if (evt.getClickCount() == 2){
            int linha = tb_escalas.getSelectedRow();
            pesquisarNescala = (TbEscalas.getValueAt(linha, 1).toString());
            this.dispose();
        }
    }//GEN-LAST:event_tb_escalasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesquisarEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesquisarEscala dialog = new frmPesquisarEscala(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btn_pesquisarCompra;
    javax.swing.JComboBox<String> cb_Destino;
    javax.swing.JComboBox<String> cb_Origem;
    javax.swing.JTable tb_escalas;
    com.toedter.calendar.JDateChooser txt_dtFinal;
    com.toedter.calendar.JDateChooser txt_dtInicial;
    // End of variables declaration//GEN-END:variables

private void buscarEscalas(){
    
        String SQLSelection = "select escalaAbate_idVenda as nVenda,"
                + "escalaAbate_id as nEscala,"
                + "escalaAbate_origem as Origem,"
                + "escalaAbate_dtEmbarque as DtEmbarque,"
                + "escalaAbate_categoria as Categoria,"
                + "escalaAbate_destino as Destino,"
                + "escalaAbate_qtEscala as QEscala,"
                + "ifnull((select Sum(saida_gado_qNF) from saida_gado where saida_gado_nEscala = escalaAbate_id),0) as QNF,"
                + "ifnull((select SUM(saida_gta_mT + saida_gta_fT) from saida_gta sgta , saida_gado sg  Where ex.escalaAbate_id = sg.saida_gado_nEscala And sg.saida_gado_id = sgta.saida_gta_idSaida) ,0) as QGTA,"
                + "@QMIN:=ifnull((select Sum(saida_gado_qMin) from saida_gado where saida_gado_nEscala = escalaAbate_id),0) as QMin,"
                + "@PVT:=ifnull((select Sum(saida_gado_pesoL) from saida_gado where saida_gado_nEscala = escalaAbate_id),0) as PesoTotal,"
                + "format(@PVT/@QMIN,2) as PesoM "
                + "From escala_abate ex "
                + "Where escalaAbate_dtEmbarque Between ? and ? and escalaAbate_origem like '%" + Origem + "%' and escalaAbate_destino like '%" + Destino + "%';";

        try {
            PreparedStatement st = Conexao.getConnection().prepareStatement(SQLSelection);
            st.setString(1, Corretores.ConverterParaSQL( new SimpleDateFormat("dd/MM/yyyy").format(txt_dtInicial.getDate())));
            st.setString(2, Corretores.ConverterParaSQL( new SimpleDateFormat("dd/MM/yyyy").format(txt_dtFinal.getDate())));
            ResultSet rs = st.executeQuery();
           TbEscalas.setNumRows(0);
            while(rs.next()){
                
                TbEscalas.addRow(new Object[]{rs.getInt("nVenda"), rs.getInt("nEscala"), rs.getString("Origem"), Corretores.ConverterParaJava(rs.getString("DtEmbarque")), rs.getString("Categoria"), rs.getString("Destino"), rs.getInt("QEscala"), rs.getInt("QNF"), rs.getInt("QGTA"), rs.getInt("QMIN"), new DecimalFormat("#,###,##0.0 kg").format(rs.getDouble("PesoTotal")), new DecimalFormat("#,##0.0 kg").format(rs.getDouble("PesoM"))    });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex + " Erro ao buscar escalas!", "Erro", 0, FormatarICO.ICObtnSair());  
        }

    }










}
