/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.ListFazendasBeans;
import Beans.RelatoriosFinanceirosBeans;
import DAO.Diversas;
import DAO.RelatoriosFinanceirosDAO;
import static GUI.Principal.ListFazendas;
import Icones.FormatarICO;
import Utilitarios.CentralizarTabela;
import Utilitarios.Corretores;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.ToolTipManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class frmRelBovino extends javax.swing.JInternalFrame {

    
    CentralizarTabela Centralizar;
    Diversas DiversasD;
    frmRelatorioMinutas RelatorioMinutas;
    frmGTA ControleGTA;
    frmRelEntradaGado RelatorioEntradaGado;
    
    public frmRelBovino() {
        initComponents();
       
        Centralizar = new CentralizarTabela();
        DiversasD = new Diversas();
      

    }
    
    

   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        jPopMenu = new javax.swing.JPopupMenu();
        jMenuEditarPagto = new javax.swing.JMenuItem();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        jMenu_entradaGTA = new javax.swing.JCheckBoxMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu_minutas = new javax.swing.JCheckBoxMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        jMenu_entradaGadoDiario = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jm_extrato_cc = new javax.swing.JMenuItem();

        jMenuEditarPagto.setText("Editar Pagamento");
        jMenuEditarPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarPagtoActionPerformed(evt);
            }
        });
        jPopMenu.add(jMenuEditarPagto);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Relatórios de Gado");
        getContentPane().setLayout(null);

        jMenu1.setText("Exibir");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu_entradaGTA.setText("Movimento de GTA's");
        jMenu_entradaGTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_entradaGTAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu_entradaGTA);
        jMenu1.add(jSeparator3);

        jMenu_minutas.setText("Movimento de Minutas");
        jMenu_minutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_minutasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu_minutas);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu_entradaGadoDiario.setText("Entrada de Gado");
        jMenu_entradaGadoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_entradaGadoDiarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu_entradaGadoDiario);
        jMenu2.add(jSeparator5);

        jm_extrato_cc.setText("Compra de Gado");
        jMenu2.add(jm_extrato_cc);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1366, 669);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEditarPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarPagtoActionPerformed
    
    }//GEN-LAST:event_jMenuEditarPagtoActionPerformed

    private void jMenu_minutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_minutasActionPerformed
        RelatorioMinutas = new frmRelatorioMinutas();
        this.add(RelatorioMinutas);
        RelatorioMinutas.setVisible(true);
    }//GEN-LAST:event_jMenu_minutasActionPerformed

    private void jMenu_entradaGTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_entradaGTAActionPerformed
        ControleGTA = new frmGTA();
        this.add(ControleGTA);
        ControleGTA.setVisible(true);
    }//GEN-LAST:event_jMenu_entradaGTAActionPerformed

    private void jMenu_entradaGadoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_entradaGadoDiarioActionPerformed
        RelatorioEntradaGado = new frmRelEntradaGado(null, true);
        RelatorioEntradaGado.setLocationRelativeTo(null);
        RelatorioEntradaGado.setVisible(true);
    }//GEN-LAST:event_jMenu_entradaGadoDiarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem jMenuEditarPagto;
    javax.swing.JCheckBoxMenuItem jMenu_entradaGTA;
    javax.swing.JMenuItem jMenu_entradaGadoDiario;
    javax.swing.JCheckBoxMenuItem jMenu_minutas;
    javax.swing.JPopupMenu jPopMenu;
    javax.swing.JPopupMenu.Separator jSeparator5;
    javax.swing.JMenuItem jm_extrato_cc;
    // End of variables declaration//GEN-END:variables

    

    


}

