/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.AnoSafra;
import Beans.CultivoBeans;
import Beans.CulturaBeans;
import Beans.ListFazendasBeans;
import Beans.TalhaoBeans;
import Beans.OrdemServicoBeans;
import DAO.Diversas;
import TreeModel.CheckRenderer;
import TreeModel.FazendasTreeModel;
import TreeModel.NodeSelectionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JTree;
import javax.swing.table.TableModel;
import javax.swing.tree.TreePath;
import org.jdesktop.swingx.JXTreeTable;

/**
 *
 * @author agroa
 */
public class frmRelatorioOperacoes extends javax.swing.JInternalFrame {

    NodeSelectionListener NodeSelectionListener;
    FazendasTreeModel treeModel;
    Diversas DiversasD;
    List<ListFazendasBeans> listFazendas;
    List<AnoSafra> listAnoSafra;
    List<CultivoBeans> listCultivo;
    List<CulturaBeans> listCultura;
    List<TalhaoBeans> listTalhao;
    List<TalhaoBeans> listTalhaoSelect;
    List<OrdemServicoBeans> listOrdemServico;

    public frmRelatorioOperacoes() {
        super();
        DiversasD = new Diversas();
        initComponents();
        getTreeFazendas();

        setMaximumSize();
        getTreeTableOperacao();
    }

    private void setMaximumSize() {


    }

    private JTree getTreeFazendas() {
        tree_fazendas.setModel(getTreeModel());
        //tree_fazendas.setCellRenderer(new CheckRenderer());
        // tree_fazendas.addMouseListener(getNodeListener(tree_fazendas));
        tree_fazendas.setRootVisible(false);
        tree_fazendas.setShowsRootHandles(true);

        return tree_fazendas;
    }

    private JXTreeTable getTreeTableOperacao() {
    
        return tree_operacoes;
    }

    private NodeSelectionListener getNodeListener(JTree tree) {
        if (NodeSelectionListener == null) {
            NodeSelectionListener = new NodeSelectionListener(tree);
        }
        return NodeSelectionListener;
    }

    private FazendasTreeModel getTreeModel() {
        if (treeModel == null) {
            treeModel = new FazendasTreeModel(listAnoSafra());
        }

        return treeModel;
    }

    private List<AnoSafra> listAnoSafra() {

        listFazendas = DiversasD.ListpmFazenda();
        listCultivo = DiversasD.ListCultivo();
        listAnoSafra = DiversasD.listAnoSafra();
        listCultura = DiversasD.ListCultura();
        listTalhao = DiversasD.ListTalhao();
        listTalhaoSelect = new ArrayList<>();
        for (int i = 0; i < listAnoSafra.size(); i++) {
            for (int j = 0; j < listCultivo.size(); j++) {
                for (int k = 0; k < listCultura.size(); k++) {
                    for (int x = 0; x < listFazendas.size(); x++) {
                        listTalhaoSelect = new ArrayList<>();
                        for (int y = 0; y < listTalhao.size(); y++) {
                            if (listTalhao.get(y).getIdFazenda() == listFazendas.get(x).getID()) {
                                listTalhaoSelect.add(listTalhao.get(y));
                            }
                        }
                        listFazendas.get(x).setListTalhoes(listTalhaoSelect);
                    }
                    listCultura.get(k).setListFazendas(listFazendas);
                }
                listCultivo.get(j).setListCultura(listCultura);
            }
            listAnoSafra.get(i).setListCultivos(listCultivo);
        }

        return listAnoSafra;
    }

    private void carregarTalhaoes() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tree_fazendas = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tree_operacoes = new org.jdesktop.swingx.JXTreeTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Resumo de Operações");

        tree_fazendas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fazendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        tree_fazendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree_fazendas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree_fazendas.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                tree_fazendasTreeExpanded(evt);
            }
        });
        tree_fazendas.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                tree_fazendasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tree_fazendas);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jScrollPane4.setViewportView(tree_operacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tree_fazendasTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_tree_fazendasTreeExpanded

    }//GEN-LAST:event_tree_fazendasTreeExpanded

    private void tree_fazendasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_tree_fazendasValueChanged
        TreePath path = evt.getPath();
        if (path != null) {
            if (path.getLastPathComponent() instanceof TalhaoBeans) {
                TalhaoBeans node = (TalhaoBeans) path.getLastPathComponent();

            }
        }
    }//GEN-LAST:event_tree_fazendasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTree tree_fazendas;
    private org.jdesktop.swingx.JXTreeTable tree_operacoes;
    // End of variables declaration//GEN-END:variables
}
