/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.SaidaGadoBeans;
import Controller.SaidaGadoController;
import DAO.SaidaGadoDAO;
import static GUI.frmPesquisarEscala.pesquisarNescala;
import Icones.FormatarICO;
import Utilitarios.CentralizarTabela;
import Utilitarios.Corretores;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Bruno
 */
public class frmSaidaGado extends javax.swing.JInternalFrame {

    SaidaGadoDAO SaidaD;
    SaidaGadoBeans SaidaB;
    SaidaGadoController SaidaC;
    DefaultTableModel TbSaida;
    DefaultTableModel TbGTASaida;
    DefaultTableModel TbSaidaResumo;
    JComboBox BoxOrigem;
    JComboBox BoxDestino;
    TableColumn ColumnDestino;
    MaskFormatter FormatoPlaca;
    frmPesquisarEscala telaPesquisarEscala;
    DefaultTableCellRenderer cellRender;
    CentralizarTabela Centralizar;

    public frmSaidaGado() {
        initComponents();
        SaidaD = new SaidaGadoDAO();
        SaidaB = new SaidaGadoBeans();
        SaidaC = new SaidaGadoController();

        TbGTASaida = (DefaultTableModel) tb_gta.getModel();
        TbSaida = (DefaultTableModel) tb_saida.getModel();
        TbSaidaResumo = (DefaultTableModel) tb_saidaResumo.getModel();
        ArrayList FazendaOrigem = SaidaD.fazendaOrigem();
        ArrayList Transportadora = SaidaD.buscarTransportadora();
        cb_origGado.setModel(new DefaultComboBoxModel(new Vector(FazendaOrigem)));
        cb_pOrigem.setModel(new DefaultComboBoxModel(new Vector(FazendaOrigem)));
        cb_transp.setModel(new DefaultComboBoxModel(new Vector(Transportadora)));
        cb_pTrans.setModel(new DefaultComboBoxModel(new Vector(Transportadora)));
        txt_pDtInicial.setDate(Corretores.PrimeiroDiaMes());
        txt_pDtFinal.setDate(Corretores.UltimoDiaMes());

        SaidaB.setOrigem("");
        SaidaD.preencherTabela(SaidaB, TbSaida);

        BoxOrigem = new JComboBox();
        BoxDestino = new JComboBox();
        BoxOrigem.setModel(new DefaultComboBoxModel(new Vector(SaidaD.fazendaOrigem())));
        ColumnDestino = tb_gta.getColumnModel().getColumn(2);
        TableColumn FazOrigem = tb_gta.getColumnModel().getColumn(1);
        FazOrigem.setCellEditor(new DefaultCellEditor(BoxOrigem));

        getTableResumo();

    }

    private JTable getTableResumo() {
        Centralizar = new CentralizarTabela();
        Centralizar.centralizarTabela(tb_saidaResumo);
        ((DefaultTableCellRenderer) tb_saidaResumo.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        tb_saidaResumo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        ((DefaultTableCellRenderer) tb_saida.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        ((DefaultTableCellRenderer) tb_gta.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        
        cellRender = new DefaultTableCellRenderer();
        cellRender.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tb_gta.getColumnCount(); i++) {
            tb_gta.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        }
        for (int i = 0; i < tb_saida.getColumnCount(); i++) {
            tb_saida.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        }
        return tb_saidaResumo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        txt_nNF = new javax.swing.JTextField();
        txt_valorNF = new javax.swing.JTextField();
        txt_qNF = new javax.swing.JTextField();
        txt_pesoM = new javax.swing.JTextField();
        cb_categoria = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
        cb_origGado = new javax.swing.JComboBox<>();
        txt_pesoL = new javax.swing.JTextField();
        javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        txt_nMin = new javax.swing.JTextField();
        txt_pesoB = new javax.swing.JTextField();
        javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        txt_tara = new javax.swing.JTextField();
        cb_transp = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
        txt_qMin = new javax.swing.JTextField();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        try {

            FormatoPlaca = new MaskFormatter("AAA-####");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao criar máscara", "Erro", 0);
        }
        txt_placa = new JFormattedTextField(FormatoPlaca);
        cb_destino = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        js_nTabela = new javax.swing.JSpinner();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        tb_gta = new javax.swing.JTable();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        txt_observacao = new javax.swing.JTextArea();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tb_saida = new javax.swing.JTable();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        txt_pDtInicial = new com.toedter.calendar.JDateChooser();
        txt_pDtFinal = new com.toedter.calendar.JDateChooser();
        cb_pMotivo = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
        cb_pOrigem = new javax.swing.JComboBox<>();
        cb_pDestino = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel25 = new javax.swing.JLabel();
        cb_pTrans = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel26 = new javax.swing.JLabel();
        txt_pNF = new javax.swing.JTextField();
        javax.swing.JLabel jLabel27 = new javax.swing.JLabel();
        txt_pGTA = new javax.swing.JTextField();
        javax.swing.JLabel jLabel28 = new javax.swing.JLabel();
        txt_pMin = new javax.swing.JTextField();
        btn_pSaidas = new javax.swing.JButton();
        javax.swing.JLabel jLabel29 = new javax.swing.JLabel();
        txt_pNEscala = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        tb_saidaResumo = new javax.swing.JTable();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel30 = new javax.swing.JLabel();
        txt_totalGTA = new javax.swing.JTextField();
        javax.swing.JLabel jLabel31 = new javax.swing.JLabel();
        txt_totalMin = new javax.swing.JTextField();
        javax.swing.JLabel jLabel32 = new javax.swing.JLabel();
        txt_pesoMTotal = new javax.swing.JTextField();
        txt_idSaida = new javax.swing.JTextField();
        txt_nEscala = new javax.swing.JTextField();
        txt_dtSaida = new com.toedter.calendar.JDateChooser();
        cb_motivo = new javax.swing.JComboBox<>();
        btn_pesquisarCompra = new javax.swing.JButton();
        ch_trava = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Saída de Gado");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Saída");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Motivo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nº Escala");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nº NF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor NF");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Qt NF");

        txt_nNF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nNF.setEnabled(false);
        txt_nNF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nNFFocusLost(evt);
            }
        });

        txt_valorNF.setEnabled(false);
        txt_valorNF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_valorNFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_valorNFFocusLost(evt);
            }
        });

        txt_qNF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qNF.setEnabled(false);
        txt_qNF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qNFFocusLost(evt);
            }
        });

        txt_pesoM.setEditable(false);
        txt_pesoM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pesoM.setEnabled(false);

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Touros", "Vaca Parida", "Vaca Descarte", "Vaca Solteira", "Vacas", "Novilhas", "Bezerras", "Bezerros", "Garrotes", "Bois Magros", "Bois" }));
        cb_categoria.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Categoria");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Peso M.");

        cb_origGado.setEnabled(false);

        txt_pesoL.setEditable(false);
        txt_pesoL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pesoL.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Peso L.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Destino");

        txt_nMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nMin.setEnabled(false);
        txt_nMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nMinFocusLost(evt);
            }
        });

        txt_pesoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pesoB.setEnabled(false);
        txt_pesoB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pesoBFocusLost(evt);
            }
        });
        txt_pesoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pesoBKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Peso B.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Nº Min");

        txt_tara.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tara.setEnabled(false);
        txt_tara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_taraFocusLost(evt);
            }
        });
        txt_tara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_taraKeyReleased(evt);
            }
        });

        cb_transp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cb_transp.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Tara");

        txt_qMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_qMin.setEnabled(false);
        txt_qMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qMinFocusLost(evt);
            }
        });
        txt_qMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qMinKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Transportadora");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Qt Min");

        txt_placa.setEnabled(false);

        cb_destino.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Origem");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Placa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "GTA's"));

        js_nTabela.setModel(new javax.swing.SpinnerNumberModel());
        js_nTabela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js_nTabelaStateChanged(evt);
            }
        });

        tb_gta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº GTA", "Origem GTA", "Destino GTA", "Qt GTA", "M 0-12", "M 13-24", "M 25-36", "M 36+", "Macho T", "F 0-12", "F 13-24", "F 15-36", "F 36+", "Femea T", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_gta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_gta.setEnabled(false);
        tb_gta.setGridColor(new java.awt.Color(51, 51, 255));
        tb_gta.getTableHeader().setReorderingAllowed(false);
        tb_gta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_gtaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tb_gta);
        if (tb_gta.getColumnModel().getColumnCount() > 0) {
            tb_gta.getColumnModel().getColumn(0).setResizable(false);
            tb_gta.getColumnModel().getColumn(1).setResizable(false);
            tb_gta.getColumnModel().getColumn(1).setPreferredWidth(150);
            tb_gta.getColumnModel().getColumn(2).setResizable(false);
            tb_gta.getColumnModel().getColumn(2).setPreferredWidth(150);
            tb_gta.getColumnModel().getColumn(3).setResizable(false);
            tb_gta.getColumnModel().getColumn(4).setResizable(false);
            tb_gta.getColumnModel().getColumn(5).setResizable(false);
            tb_gta.getColumnModel().getColumn(6).setResizable(false);
            tb_gta.getColumnModel().getColumn(7).setResizable(false);
            tb_gta.getColumnModel().getColumn(8).setResizable(false);
            tb_gta.getColumnModel().getColumn(9).setResizable(false);
            tb_gta.getColumnModel().getColumn(10).setResizable(false);
            tb_gta.getColumnModel().getColumn(11).setResizable(false);
            tb_gta.getColumnModel().getColumn(12).setResizable(false);
            tb_gta.getColumnModel().getColumn(13).setResizable(false);
            tb_gta.getColumnModel().getColumn(14).setResizable(false);
            tb_gta.getColumnModel().getColumn(14).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(js_nTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(js_nTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Observação");

        txt_observacao.setColumns(20);
        txt_observacao.setRows(5);
        txt_observacao.setEnabled(false);
        jScrollPane3.setViewportView(txt_observacao);

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/deletar_40x40.png"))); // NOI18N
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/editar_pequeno.png"))); // NOI18N
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salvar.png"))); // NOI18N
        btn_Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Salvar.setDisabledIcon(null);
        btn_Salvar.setEnabled(false);
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir_40x40.png"))); // NOI18N
        btn_novo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        tb_saida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_saida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data Saída", "Motivo", "Nº Esc", "Nº NF", "Valor NF", "Origem", "Destino", "Transportadora", "Nº Min", "Placa", "Tara", "Peso B", "Peso L", "Peso M", "Categoria", "Qt NF", "Qt GTA", "Qt Min", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_saidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_saida);
        if (tb_saida.getColumnModel().getColumnCount() > 0) {
            tb_saida.getColumnModel().getColumn(0).setMinWidth(50);
            tb_saida.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_saida.getColumnModel().getColumn(0).setMaxWidth(50);
            tb_saida.getColumnModel().getColumn(1).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(1).setPreferredWidth(90);
            tb_saida.getColumnModel().getColumn(1).setMaxWidth(90);
            tb_saida.getColumnModel().getColumn(2).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(2).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(2).setMaxWidth(90);
            tb_saida.getColumnModel().getColumn(3).setMinWidth(60);
            tb_saida.getColumnModel().getColumn(3).setPreferredWidth(60);
            tb_saida.getColumnModel().getColumn(3).setMaxWidth(80);
            tb_saida.getColumnModel().getColumn(4).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(4).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(4).setMaxWidth(90);
            tb_saida.getColumnModel().getColumn(5).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(5).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(5).setMaxWidth(0);
            tb_saida.getColumnModel().getColumn(6).setMinWidth(90);
            tb_saida.getColumnModel().getColumn(6).setPreferredWidth(90);
            tb_saida.getColumnModel().getColumn(6).setMaxWidth(120);
            tb_saida.getColumnModel().getColumn(7).setMinWidth(90);
            tb_saida.getColumnModel().getColumn(7).setPreferredWidth(90);
            tb_saida.getColumnModel().getColumn(7).setMaxWidth(120);
            tb_saida.getColumnModel().getColumn(8).setMinWidth(90);
            tb_saida.getColumnModel().getColumn(8).setPreferredWidth(90);
            tb_saida.getColumnModel().getColumn(8).setMaxWidth(150);
            tb_saida.getColumnModel().getColumn(9).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(9).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(9).setMaxWidth(90);
            tb_saida.getColumnModel().getColumn(10).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(10).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(10).setMaxWidth(90);
            tb_saida.getColumnModel().getColumn(11).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(11).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(11).setMaxWidth(0);
            tb_saida.getColumnModel().getColumn(12).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(12).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(12).setMaxWidth(0);
            tb_saida.getColumnModel().getColumn(13).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(13).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(13).setMaxWidth(0);
            tb_saida.getColumnModel().getColumn(14).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(14).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(14).setMaxWidth(100);
            tb_saida.getColumnModel().getColumn(15).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(15).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(15).setMaxWidth(0);
            tb_saida.getColumnModel().getColumn(16).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(16).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(16).setMaxWidth(70);
            tb_saida.getColumnModel().getColumn(17).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(17).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(17).setMaxWidth(70);
            tb_saida.getColumnModel().getColumn(18).setMinWidth(70);
            tb_saida.getColumnModel().getColumn(18).setPreferredWidth(70);
            tb_saida.getColumnModel().getColumn(18).setMaxWidth(70);
            tb_saida.getColumnModel().getColumn(19).setMinWidth(0);
            tb_saida.getColumnModel().getColumn(19).setPreferredWidth(0);
            tb_saida.getColumnModel().getColumn(19).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nNF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_valorNF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_qNF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cb_origGado, 0, 145, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_transp, 0, 203, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nMin, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_qMin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_tara, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 48, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cb_destino, 0, 141, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cb_categoria, 0, 117, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pesoL, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_pesoM, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_nNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valorNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cb_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cb_transp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cb_origGado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel23)
                    .addComponent(txt_pesoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pesoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txt_pesoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txt_tara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txt_qMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Saída", jPanel4);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Data Inicial");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Data Final");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Motivo");

        cb_pMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Venda", "Transf (-)", "Abate Interno", "Morte", "Era", "Outras", " " }));
        cb_pMotivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_pMotivoItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Origem");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Destino");

        cb_pDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Transp");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Nº NF");

        txt_pNF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Nº GTA");

        txt_pGTA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Nº Min");

        txt_pMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_pSaidas.setBackground(new java.awt.Color(255, 255, 255));
        btn_pSaidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/buscar.png"))); // NOI18N
        btn_pSaidas.setOpaque(false);
        btn_pSaidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pSaidasActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Nº Escala");

        txt_pNEscala.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tb_saidaResumo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_saidaResumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data Saída", "Motivo", "Nº Esc", "Nº NF", "Valor NF", "Origem", "Destino", "Transportadora", "Nº Min", "Placa", "Tara", "Peso B", "Peso L", "Peso M", "Categoria", "Qt NF", "Qt GTA", "Qt Min", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_saidaResumo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_saidaResumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_saidaResumoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_saidaResumo);
        if (tb_saidaResumo.getColumnModel().getColumnCount() > 0) {
            tb_saidaResumo.getColumnModel().getColumn(0).setMinWidth(50);
            tb_saidaResumo.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_saidaResumo.getColumnModel().getColumn(0).setMaxWidth(50);
            tb_saidaResumo.getColumnModel().getColumn(1).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(1).setPreferredWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(1).setMaxWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(2).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(2).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(2).setMaxWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(3).setMinWidth(60);
            tb_saidaResumo.getColumnModel().getColumn(3).setPreferredWidth(60);
            tb_saidaResumo.getColumnModel().getColumn(3).setMaxWidth(80);
            tb_saidaResumo.getColumnModel().getColumn(4).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(4).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(4).setMaxWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(5).setMinWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(5).setPreferredWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(5).setMaxWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(6).setMinWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(6).setPreferredWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(6).setMaxWidth(120);
            tb_saidaResumo.getColumnModel().getColumn(7).setMinWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(7).setPreferredWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(7).setMaxWidth(120);
            tb_saidaResumo.getColumnModel().getColumn(8).setMinWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(8).setPreferredWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(8).setMaxWidth(150);
            tb_saidaResumo.getColumnModel().getColumn(9).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(9).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(9).setMaxWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(10).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(10).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(10).setMaxWidth(90);
            tb_saidaResumo.getColumnModel().getColumn(11).setMinWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(11).setPreferredWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(11).setMaxWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(12).setMinWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(12).setPreferredWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(12).setMaxWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(13).setPreferredWidth(100);
            tb_saidaResumo.getColumnModel().getColumn(14).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(14).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(14).setMaxWidth(100);
            tb_saidaResumo.getColumnModel().getColumn(15).setMinWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(15).setPreferredWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(15).setMaxWidth(0);
            tb_saidaResumo.getColumnModel().getColumn(16).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(16).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(16).setMaxWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(17).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(17).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(17).setMaxWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(18).setMinWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(18).setPreferredWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(18).setMaxWidth(70);
            tb_saidaResumo.getColumnModel().getColumn(19).setPreferredWidth(100);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Total GTA");

        txt_totalGTA.setEditable(false);
        txt_totalGTA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Total Min");

        txt_totalMin.setEditable(false);
        txt_totalMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Peso Médio");

        txt_pesoMTotal.setEditable(false);
        txt_pesoMTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pesoMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalGTA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(txt_pesoMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(txt_totalGTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(txt_totalMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pDtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txt_pDtInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_pMotivo, 0, 99, Short.MAX_VALUE)
                            .addComponent(txt_pNEscala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pNF)
                            .addComponent(cb_pOrigem, 0, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pGTA)
                            .addComponent(cb_pDestino, 0, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_pTrans, 0, 121, Short.MAX_VALUE)
                            .addComponent(txt_pMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_pSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pDtInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(cb_pMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(cb_pOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(cb_pDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)
                                .addComponent(cb_pTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_pDtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(txt_pNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(txt_pGTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)))
                            .addComponent(txt_pMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(txt_pNEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btn_pSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Resumo de Saída", jPanel5);

        txt_idSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_nEscala.setEditable(false);
        txt_nEscala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nEscala.setText("0");
        txt_nEscala.setEnabled(false);

        txt_dtSaida.setEnabled(false);

        cb_motivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Venda", "Transf (-)", "Abate Interno", "Morte", "Era", "Outras", " " }));
        cb_motivo.setEnabled(false);
        cb_motivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_motivoItemStateChanged(evt);
            }
        });

        btn_pesquisarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/buscar pequeno.png"))); // NOI18N
        btn_pesquisarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarCompraActionPerformed(evt);
            }
        });

        ch_trava.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ch_trava.setText("Bloquear Cabeçalho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_idSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ch_trava)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ch_trava)
                    .addComponent(btn_pesquisarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txt_nEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cb_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dtSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setBounds(0, 0, 1045, 625);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        btn_Salvar.setEnabled(true);
        btn_editar.setEnabled(false);
        txt_idSaida.setEnabled(false);
        habilitarCampos();
        limparCampos();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        int cadastrar = JOptionPane.showConfirmDialog(null, "Deseja Salvar esta Saída de Gado?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (cadastrar == JOptionPane.YES_OPTION) {
            if (verificarCampos() == true) {
                popularBeans();
                if (SaidaD.inserirGta(TbGTASaida, SaidaB)) {
                    SaidaD.preencherTabela(SaidaB, TbSaida);
                    limparCampos();
                    desabilitarCampos();
                }
            }
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int editar = JOptionPane.showConfirmDialog(null, "Deseja editar esta Saída de Gado?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (editar == JOptionPane.YES_OPTION) {
            if (!txt_idSaida.getText().equals("")) {
                popularBeans();
                if (verificarCampos() == true) {
                    SaidaD.editarRegistro(TbGTASaida, Integer.parseInt(txt_idSaida.getText()), SaidaB);
                    SaidaD.preencherTabela(SaidaB, TbSaida);
                    limparCampos();
                    desabilitarCampos();
                    btn_editar.setEnabled(false);
                    btn_excluir.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione a Saída que deseja editar!", "Erro", 0, FormatarICO.ICObtnSair());
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int excluir = JOptionPane.showConfirmDialog(null, "Deseja excluir esta Saída de Gado?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (excluir == JOptionPane.YES_OPTION) {
            SaidaC.excluirRegistroController(Integer.parseInt(txt_idSaida.getText()));
            limparCampos();
            desabilitarCampos();
            btn_editar.setEnabled(false);
            btn_excluir.setEnabled(false);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void cb_motivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_motivoItemStateChanged
        cb_destino.removeAllItems();
        BoxDestino.removeAllItems();
        if (cb_motivo.getSelectedItem().toString().equals("Transf (-)")) {
            ArrayList FazendaDestino = SaidaD.preencherFazendaDestino();
            cb_destino.setModel(new DefaultComboBoxModel(new Vector(FazendaDestino)));
            BoxDestino.setModel(new DefaultComboBoxModel(new Vector(FazendaDestino)));
            ColumnDestino.setCellEditor(new DefaultCellEditor(BoxDestino));
            txt_nEscala.setText("0");
            txt_nEscala.setEnabled(false);
        } else if (cb_motivo.getSelectedItem().toString().equals("Venda")) {
            ArrayList clientes = SaidaD.buscarClientes();
            cb_destino.setModel(new DefaultComboBoxModel(new Vector(clientes)));
            BoxDestino.setModel(new DefaultComboBoxModel(new Vector(clientes)));
            ColumnDestino.setCellEditor(new DefaultCellEditor(BoxDestino));
            txt_nEscala.setText("0");
            txt_nEscala.setEnabled(true);
        } else {
            cb_destino.addItem("-");
        }
    }//GEN-LAST:event_cb_motivoItemStateChanged

    private void txt_taraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_taraKeyReleased
        calcularPesoM();
    }//GEN-LAST:event_txt_taraKeyReleased

    private void txt_pesoBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesoBKeyReleased
        calcularPesoM();
    }//GEN-LAST:event_txt_pesoBKeyReleased

    private void txt_qMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qMinKeyReleased
        calcularPesoM();
    }//GEN-LAST:event_txt_qMinKeyReleased

    private void txt_taraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_taraFocusLost
        txt_tara.setText(Corretores.ConverterDoubleQuilos(txt_tara.getText()));
    }//GEN-LAST:event_txt_taraFocusLost

    private void txt_pesoBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoBFocusLost
        txt_pesoB.setText(Corretores.ConverterDoubleQuilos(txt_pesoB.getText()));
    }//GEN-LAST:event_txt_pesoBFocusLost

    private void txt_valorNFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_valorNFFocusLost
        txt_valorNF.setText(Corretores.ConverterDecimalReais(txt_valorNF.getText()));
    }//GEN-LAST:event_txt_valorNFFocusLost

    private void tb_gtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_gtaKeyReleased
        somarGTAm();
        somarGTAf();
    }//GEN-LAST:event_tb_gtaKeyReleased

    private void js_nTabelaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js_nTabelaStateChanged
        if (Integer.parseInt(js_nTabela.getValue().toString()) >= 0) {
            TbGTASaida.addRow(new Object[]{"", "-", "-", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
            TbGTASaida.setNumRows(Integer.parseInt(js_nTabela.getValue().toString()));
        } else {
            js_nTabela.setValue(0);
        }
    }//GEN-LAST:event_js_nTabelaStateChanged

    private void btn_pesquisarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarCompraActionPerformed
        telaPesquisarEscala = new frmPesquisarEscala(null, true);
        telaPesquisarEscala.setVisible(true);
        txt_nEscala.setText(pesquisarNescala);
    }//GEN-LAST:event_btn_pesquisarCompraActionPerformed

    private void btn_pSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pSaidasActionPerformed
        popularBeansPesquisa();
        SaidaC.preencherTabelaResumo(SaidaB, TbSaidaResumo);
        totalizarResumo();
    }//GEN-LAST:event_btn_pSaidasActionPerformed

    private void tb_saidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_saidaMouseClicked

        if (evt.getClickCount() != 2) {
            limparCampos();
            btn_editar.setEnabled(false);
            btn_excluir.setEnabled(false);
            js_nTabela.setValue(0);
        }

        if (evt.getClickCount() == 2) {
            int linha = tb_saida.getSelectedRow();
            preencherCampos(linha);
            TbGTASaida.setNumRows(0);
            SaidaD.buscarRegistroGTA(TbGTASaida, Integer.parseInt(TbSaida.getValueAt(linha, 0).toString()));
            js_nTabela.setValue(TbGTASaida.getRowCount());
            habilitarCampos();
            txt_idSaida.setEnabled(false);
            btn_excluir.setEnabled(true);
            btn_editar.setEnabled(true);
            btn_Salvar.setEnabled(false);
        }


    }//GEN-LAST:event_tb_saidaMouseClicked

    private void tb_saidaResumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_saidaResumoMouseClicked
        if (evt.getClickCount() != 2) {
            limparCampos();
            btn_editar.setEnabled(false);
            btn_excluir.setEnabled(false);
            js_nTabela.setValue(0);
        }

        if (evt.getClickCount() == 2) {
            int linha = tb_saidaResumo.getSelectedRow();
            preencherCampos(linha);
            TbGTASaida.setNumRows(0);
            SaidaD.buscarRegistroGTA(TbGTASaida, Integer.parseInt(TbSaidaResumo.getValueAt(linha, 0).toString()));
            js_nTabela.setValue(TbGTASaida.getRowCount());
            habilitarCampos();
            txt_idSaida.setEnabled(false);
            btn_excluir.setEnabled(true);
            btn_editar.setEnabled(true);
            btn_Salvar.setEnabled(false);
            jTabbedPane1.setSelectedIndex(0);

        }
    }//GEN-LAST:event_tb_saidaResumoMouseClicked

    private void cb_pMotivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_pMotivoItemStateChanged
        if (cb_pMotivo.getSelectedItem().toString().equals("Transf (-)")) {
            ArrayList FazendaDestino = SaidaD.preencherFazendaDestino();
            cb_pDestino.setModel(new DefaultComboBoxModel(new Vector(FazendaDestino)));
        } else if (cb_pMotivo.getSelectedItem().toString().equals("Venda")) {
            ArrayList clientes = SaidaD.buscarClientes();
            cb_pDestino.setModel(new DefaultComboBoxModel(new Vector(clientes)));
        } else {
            cb_pDestino.addItem("-");
        }
    }//GEN-LAST:event_cb_pMotivoItemStateChanged

    private void txt_valorNFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_valorNFFocusGained
        txt_valorNF.selectAll();
    }//GEN-LAST:event_txt_valorNFFocusGained

    private void txt_nMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nMinFocusLost
        getInteger(txt_nMin.getText());
    }//GEN-LAST:event_txt_nMinFocusLost

    private void txt_qNFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qNFFocusLost
        getInteger(txt_qNF.getText());
    }//GEN-LAST:event_txt_qNFFocusLost

    private void txt_nNFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nNFFocusLost
        getInteger(txt_nNF.getText());
    }//GEN-LAST:event_txt_nNFFocusLost

    private void txt_qMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qMinFocusLost
        getInteger(txt_qMin.getText());
    }//GEN-LAST:event_txt_qMinFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btn_Salvar;
    javax.swing.JButton btn_editar;
    javax.swing.JButton btn_excluir;
    javax.swing.JButton btn_novo;
    javax.swing.JButton btn_pSaidas;
    javax.swing.JButton btn_pesquisarCompra;
    javax.swing.JComboBox<String> cb_categoria;
    javax.swing.JComboBox<String> cb_destino;
    javax.swing.JComboBox<String> cb_motivo;
    javax.swing.JComboBox<String> cb_origGado;
    javax.swing.JComboBox<String> cb_pDestino;
    javax.swing.JComboBox<String> cb_pMotivo;
    javax.swing.JComboBox<String> cb_pOrigem;
    javax.swing.JComboBox<String> cb_pTrans;
    javax.swing.JComboBox<String> cb_transp;
    javax.swing.JCheckBox ch_trava;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JSpinner js_nTabela;
    javax.swing.JTable tb_gta;
    javax.swing.JTable tb_saida;
    javax.swing.JTable tb_saidaResumo;
    com.toedter.calendar.JDateChooser txt_dtSaida;
    javax.swing.JTextField txt_idSaida;
    javax.swing.JTextField txt_nEscala;
    javax.swing.JTextField txt_nMin;
    javax.swing.JTextField txt_nNF;
    javax.swing.JTextArea txt_observacao;
    com.toedter.calendar.JDateChooser txt_pDtFinal;
    com.toedter.calendar.JDateChooser txt_pDtInicial;
    javax.swing.JTextField txt_pGTA;
    javax.swing.JTextField txt_pMin;
    javax.swing.JTextField txt_pNEscala;
    javax.swing.JTextField txt_pNF;
    javax.swing.JTextField txt_pesoB;
    javax.swing.JTextField txt_pesoL;
    javax.swing.JTextField txt_pesoM;
    javax.swing.JTextField txt_pesoMTotal;
    javax.swing.JTextField txt_placa;
    javax.swing.JTextField txt_qMin;
    javax.swing.JTextField txt_qNF;
    javax.swing.JTextField txt_tara;
    javax.swing.JTextField txt_totalGTA;
    javax.swing.JTextField txt_totalMin;
    javax.swing.JTextField txt_valorNF;
    // End of variables declaration//GEN-END:variables

    private void popularBeans() {
        SaidaB.setDataSaida(new SimpleDateFormat("dd/MM/yyyy").format(txt_dtSaida.getDate()));
        SaidaB.setMotivo(cb_motivo.getSelectedItem().toString());
        SaidaB.setnEscala(getInteger(txt_nEscala.getText()));
        SaidaB.setnNF((txt_nNF.getText()));
        SaidaB.setValorNF(Corretores.ConverterReaisDouble(txt_valorNF.getText()));
        SaidaB.setQtNF(Integer.parseInt(txt_qNF.getText()));
        SaidaB.setDestino(cb_destino.getSelectedItem().toString());
        SaidaB.setTransportadora(cb_transp.getSelectedItem().toString());
        SaidaB.setnMin((txt_nMin.getText()));
        SaidaB.setOrigem(cb_origGado.getSelectedItem().toString());
        SaidaB.setCategoria(cb_categoria.getSelectedItem().toString());
        SaidaB.setPlaca(txt_placa.getText());
        SaidaB.setQtMin(Integer.parseInt(txt_qMin.getText()));
        SaidaB.setTara(Corretores.ConverQuilosDouble(txt_tara.getText()));
        SaidaB.setPesoB(Corretores.ConverQuilosDouble(txt_pesoB.getText()));
        SaidaB.setPesoL(Corretores.ConverQuilosDouble(txt_pesoL.getText()));
        SaidaB.setPesoM(Corretores.ConverQuilosDouble(txt_pesoM.getText()));
        SaidaB.setObservacao(txt_observacao.getText());
    }

    private Integer getInteger(String str) {
        Integer i = 0;
        try {
            i = Integer.parseInt(str);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique o Campo Preenchido!", "Erro", 0, FormatarICO.ICObtnSair());
        }
        return i;
    }

    private void popularBeansPesquisa() {
        SaidaB.setDataInicial(new SimpleDateFormat("dd/MM/yyyy").format(txt_pDtInicial.getDate()));
        SaidaB.setDataFinal(new SimpleDateFormat("dd/MM/yyyy").format(txt_pDtFinal.getDate()));
        if (cb_pOrigem.getSelectedItem().equals("-")) {
            SaidaB.setpOrigem("");
        } else {
            SaidaB.setpOrigem(cb_pOrigem.getSelectedItem().toString());
        }
        if (cb_pMotivo.getSelectedItem().equals("-")) {
            SaidaB.setpMotivo("");
        } else {
            SaidaB.setpMotivo(cb_pMotivo.getSelectedItem().toString());
        }
        if (cb_pDestino.getSelectedItem().equals("-")) {
            SaidaB.setpDestino("");
        } else {
            SaidaB.setpDestino(cb_pDestino.getSelectedItem().toString());
        }
        if (cb_pTrans.getSelectedItem().equals("-")) {
            SaidaB.setpTrans("");
        } else {
            SaidaB.setpTrans(cb_pTrans.getSelectedItem().toString());
        }

    }

    private void preencherCampos(Integer linha) {
        //Instrução para selecionar a origem dos dados para popular os campos
        //TbSaida ou TbSaidaResumo
        DefaultTableModel OrigemDados = null;
        if (jTabbedPane1.getSelectedIndex() == 0) {
            OrigemDados = TbSaida;
        } else if (jTabbedPane1.getSelectedIndex() == 1) {
            OrigemDados = TbSaidaResumo;
        }

        try {
            txt_dtSaida.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(OrigemDados.getValueAt(linha, 1).toString()));
        } catch (ParseException ex) {
        }
        txt_idSaida.setText(OrigemDados.getValueAt(linha, 0).toString());
        cb_motivo.setSelectedItem(OrigemDados.getValueAt(linha, 2).toString());
        txt_nEscala.setText(OrigemDados.getValueAt(linha, 3).toString());
        txt_nNF.setText(OrigemDados.getValueAt(linha, 4).toString());
        txt_valorNF.setText(OrigemDados.getValueAt(linha, 5).toString());
        txt_qNF.setText(OrigemDados.getValueAt(linha, 16).toString());
        cb_origGado.setSelectedItem(OrigemDados.getValueAt(linha, 6).toString());
        cb_transp.setSelectedItem(OrigemDados.getValueAt(linha, 8).toString());
        txt_nMin.setText(OrigemDados.getValueAt(linha, 9).toString());
        cb_destino.setSelectedItem(OrigemDados.getValueAt(linha, 7).toString());
        cb_categoria.setSelectedItem(OrigemDados.getValueAt(linha, 15).toString());
        txt_placa.setText(OrigemDados.getValueAt(linha, 10).toString());
        txt_qMin.setText(OrigemDados.getValueAt(linha, 18).toString());
        txt_tara.setText(OrigemDados.getValueAt(linha, 11).toString());
        txt_pesoB.setText(OrigemDados.getValueAt(linha, 12).toString());
        txt_pesoL.setText(OrigemDados.getValueAt(linha, 13).toString());
        txt_pesoM.setText(OrigemDados.getValueAt(linha, 14).toString());

        if (OrigemDados.getValueAt(linha, 19) == null) {
            txt_observacao.setText("");
        } else {
            txt_observacao.setText(OrigemDados.getValueAt(linha, 19).toString());
        }
    }

    private boolean verificarCampos() {
        for (int i = 0; i < tb_gta.getRowCount(); i++) {
            int nDigitosGTA = TbGTASaida.getValueAt(i, 0).toString().length();
            if (nDigitosGTA != 6) {
                JOptionPane.showMessageDialog(null, "O campo Nº GTA deve conter 6 digitos", "Erro", 0, FormatarICO.ICObtnSair());
                return false;
            }
            int QmTotal = Integer.parseInt(TbGTASaida.getValueAt(i, 8).toString());
            int QfTotal = Integer.parseInt(TbGTASaida.getValueAt(i, 13).toString());
            if ((QmTotal + QfTotal) != Integer.parseInt(TbGTASaida.getValueAt(i, 3).toString()) || TbGTASaida.getValueAt(i, 3).toString().equals("0")) {
                JOptionPane.showMessageDialog(null, "Verifique a distribuíção das eras no GTA nº " + TbGTASaida.getValueAt(i, 0), "Erro", 0, FormatarICO.ICObtnSair());
                return false;
            }
            if (tb_gta.getValueAt(i, 1).toString().equals("-") || tb_gta.getValueAt(i, 2).toString().equals("-")) {
                JOptionPane.showMessageDialog(null, "Verifique o campo Origem e Destino no GTA nº " + TbGTASaida.getValueAt(i, 0), "Erro", 0, FormatarICO.ICObtnSair());
                return false;
            }
        }

        if (txt_dtSaida.getDate() == null) {
            JOptionPane.showMessageDialog(null, "O campo data deve conter uma data válida!", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        }
        if (Corretores.verificaDataMensal(txt_dtSaida.getDate())) {
        } else {
            return false;
        }

        if (cb_motivo.getSelectedItem().equals("-")) {
            JOptionPane.showMessageDialog(null, "O campo motivo deve ser preenchido!", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        } else if (cb_motivo.getSelectedItem().equals("Venda") & txt_nEscala.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Caso a saída seja uma venda, o campo Nº Escala deve estar preenchido!", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        }

        if (txt_qNF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo Quantidade na Nota Fiscal deve ser diferente de nulo!", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        }
        if (txt_qMin.getText().equals("") || txt_qMin.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "O campo Quantidade na Minuta deve ser diferente de nulo e zero!", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        }

        if (cb_motivo.getSelectedItem().equals("Morte") || cb_motivo.getSelectedItem().equals("Abate Interno")) {
            if (cb_origGado.getSelectedItem().equals("-") || cb_categoria.getSelectedItem().equals("-")) {
                JOptionPane.showMessageDialog(null, "Os campos Origem e Categoria são obrigatórios !", "Erro", 0, FormatarICO.ICObtnSair());
                return false;
            }
        } else {
            if (cb_origGado.getSelectedItem().equals("-") || cb_destino.getSelectedItem().equals("-") || cb_categoria.getSelectedItem().equals("-")) {
                JOptionPane.showMessageDialog(null, "Os campos Origem, Destino e categoria são obrigatórios !", "Erro", 0, FormatarICO.ICObtnSair());
                return false;
            }
        }
        if (!cb_transp.getSelectedItem().equals("-") & txt_nMin.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo Nº Minuta é obrigatório para caso de transporte", "Erro", 0, FormatarICO.ICObtnSair());
            return false;
        }
        return true;
    }

    final void limparCampos() {

        if (!ch_trava.isSelected()) {
            txt_idSaida.setText("");
            cb_motivo.setSelectedItem("-");
            txt_nEscala.setText("");
        }
        txt_nNF.setText("");
        txt_valorNF.setText("");
        txt_qNF.setText("");
        cb_origGado.setSelectedItem("-");
        cb_transp.setSelectedItem("-");
        txt_nMin.setText("-");
        cb_destino.setSelectedItem("-");
        cb_categoria.setSelectedItem("-");
        txt_placa.setText("");
        txt_qMin.setText("");
        txt_tara.setText("");
        txt_pesoB.setText("");
        txt_pesoL.setText("");
        txt_pesoM.setText("");
        txt_observacao.setText("");
        TbGTASaida.setNumRows(0);

    }

    final void desabilitarCampos() {
        txt_dtSaida.setEnabled(false);
        cb_motivo.setEnabled(false);
        txt_nEscala.setEnabled(false);
        txt_nNF.setEnabled(false);
        txt_valorNF.setEnabled(false);
        txt_qNF.setEnabled(false);
        cb_origGado.setEnabled(false);
        cb_transp.setEnabled(false);
        txt_nMin.setEnabled(false);
        cb_destino.setEnabled(false);
        cb_categoria.setEnabled(false);
        txt_placa.setEnabled(false);
        txt_qMin.setEnabled(false);
        txt_tara.setEnabled(false);
        txt_pesoB.setEnabled(false);
        txt_pesoL.setEnabled(false);
        txt_pesoM.setEnabled(false);
        tb_gta.setEnabled(false);
        txt_observacao.setEnabled(false);
    }

    final void habilitarCampos() {
        txt_idSaida.setEnabled(false);
        txt_dtSaida.setEnabled(true);
        cb_motivo.setEnabled(true);
        txt_nEscala.setEnabled(true);
        txt_nNF.setEnabled(true);
        txt_valorNF.setEnabled(true);
        txt_qNF.setEnabled(true);
        cb_origGado.setEnabled(true);
        cb_transp.setEnabled(true);
        txt_nMin.setEnabled(true);
        cb_destino.setEnabled(true);
        cb_categoria.setEnabled(true);
        txt_placa.setEnabled(true);
        txt_qMin.setEnabled(true);
        txt_tara.setEnabled(true);
        txt_pesoB.setEnabled(true);
        txt_pesoL.setEnabled(true);
        txt_pesoM.setEnabled(true);
        tb_gta.setEnabled(true);
        txt_observacao.setEnabled(true);
    }

    final void somarGTAm() {
        int linha = tb_gta.getSelectedRow();
        int quant = 0;
        try {
            for (int i = 4; i <= 7; i++) {
                if (tb_gta.getValueAt(linha, i).equals(0)) {
                    tb_gta.setValueAt(0, linha, i);
                }
                quant += Integer.parseInt(tb_gta.getValueAt(linha, i).toString());
            }
            tb_gta.setValueAt(quant, linha, 8);
        } catch (Exception e) {
        }

    }

    final void somarGTAf() {
        int linha = tb_gta.getSelectedRow();
        int quant = 0;

        try {
            for (int i = 9; i <= 12; i++) {
                if (tb_gta.getValueAt(linha, i).equals(0)) {
                    tb_gta.setValueAt(0, linha, i);
                }
                quant += Integer.parseInt(tb_gta.getValueAt(linha, i).toString());
            }
            tb_gta.setValueAt(quant, linha, 13);
        } catch (Exception e) {

        }
    }

    final void calcularPesoM() {
        double PesoL = 0;
        double PesoM = 0;
        int nCab = 0;
        try {
            PesoL = Corretores.ConverQuilosDouble(txt_pesoB.getText()) - Corretores.ConverQuilosDouble(txt_tara.getText());
            String Liquido = new DecimalFormat("#,##0.00").format(PesoL);
            txt_pesoL.setText(String.valueOf(Liquido));
        } catch (Exception e) {
            //  JOptionPane.showMessageDialog(null, "O campo peso bruto e tarda devem conter um númerno no formato 0.00", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
        try {
            nCab = Integer.parseInt(txt_qMin.getText());
            if (nCab > 0) {
                PesoM = (PesoL / nCab);
                String media = new DecimalFormat("#,##0.00 kg").format(PesoM);
                txt_pesoM.setText(String.valueOf(media));
            } else {
                String media = new DecimalFormat("#,##0.00 kg").format(PesoM);
                txt_pesoM.setText(String.valueOf(media));
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, "O campo número de cabeças deve conter um número inteiro", "Erro", 0, new ImageIcon("imagens/btn_sair.png"));
        }
    }

    private void totalizarResumo() {
        int totalGTA = 0;
        int totalMin = 0;
        double pesoTotal = 0.0;
        for (int i = 0; i < TbSaidaResumo.getRowCount(); i++) {
            totalGTA += Integer.parseInt(TbSaidaResumo.getValueAt(i, 17).toString());
            totalMin += Integer.parseInt(TbSaidaResumo.getValueAt(i, 18).toString());
            pesoTotal += (Corretores.ConverQuilosDouble(TbSaidaResumo.getValueAt(i, 13).toString()));
        }

        txt_totalGTA.setText(String.valueOf(totalGTA));
        txt_totalMin.setText(String.valueOf(totalMin));
        txt_pesoMTotal.setText(new DecimalFormat("0.00 kg").format(pesoTotal / totalMin));

    }

}
