/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Teste.JCollapsiblePane;
import conexaoserial.*;
import java.awt.BorderLayout;
import static java.awt.Desktop.getDesktop;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.http.HttpServlet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.border.TitledBorder;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;
import org.jdesktop.swingx.JXCollapsiblePane;
import org.apache.http.Consts;
import org.apache.http.HttpEntity;
import org.apache.http.HttpHost;
import org.apache.http.HttpRequest;
import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.conn.ClientConnectionManager;
import org.apache.http.impl.client.*;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.params.HttpParams;
import org.apache.http.protocol.HttpContext;
import org.apache.http.util.EntityUtils;

public class teste extends javax.swing.JInternalFrame {

    Main Main;
    SerialComLeitura leitura;
    JCollapsiblePane pane2;
    private HttpClient client;

    public teste() {
        //super("Main");

        initComponents();

        JButton teste = new JButton("Teste");

        pane2 = new JCollapsiblePane("Teste", this, false, false);
        pane2.setSize(new Dimension(300, 100));
        pane2.add(teste);
        pane2.setVisible(true);

        JButton toggle = new JButton(pane2.getActionMap().get(JXCollapsiblePane.TOGGLE_ACTION));
        toggle.setText("Show/Hide Search Panel");
        this.add("South", toggle);
        toggle.setVisible(true);
        System.out.println(" teste");
        client = new DefaultHttpClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JFrame jFrame1 = new javax.swing.JFrame();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txt_ler = new javax.swing.JTextField();
        btt_habilitar = new javax.swing.JToggleButton();
        btt_teste = new javax.swing.JToggleButton();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        txt_codigo = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Peso");

        txt_ler.setEditable(false);

        btt_habilitar.setText("Habilitar Leitura");
        btt_habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_habilitarActionPerformed(evt);
            }
        });

        btt_teste.setText("jToggleButton1");
        btt_teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_testeActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_ler, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btt_habilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(154, 154, 154)
                        .addComponent(btt_teste))
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btt_habilitar)
                    .addComponent(btt_teste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_habilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_habilitarActionPerformed
        if (btt_habilitar.isSelected() == true) {
            leitura = new SerialComLeitura("COM3", 9600, 100);
            leitura.HabilitarLeitura();
            leitura.ObterIdDaPorta();
            leitura.AbrirPorta();
            leitura.LerDados();
            txt_ler.setText(leitura.getPeso());
            //Controle de tempo da leitura aberta na serial
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                System.out.println("Erro na Thread: " + ex);
            }
        } else if (btt_habilitar.isSelected() == false) {
            leitura.FecharCom();
        }
    }//GEN-LAST:event_btt_habilitarActionPerformed

    private void btt_testeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_testeActionPerformed

        if (pane2.isCollapsed()) {
            pane2.setCollapsed(false);
        } else {
            pane2.setCollapsed(true);
        }


    }//GEN-LAST:event_btt_testeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            openPage();
        } catch (IOException ex) {
            Logger.getLogger(teste.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JToggleButton btt_habilitar;
    javax.swing.JToggleButton btt_teste;
    javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_ler;
    // End of variables declaration//GEN-END:variables

    private void collapsed() {
        JXCollapsiblePane cp = new JXCollapsiblePane();
        cp.setLayout(new BorderLayout());
        cp.setOrientation(JXCollapsiblePane.Orientation.VERTICAL);
        // the Controls panel with a textfield to filter the tree
        JPanel controls = new JPanel(new FlowLayout(FlowLayout.LEFT, 4, 0));
        controls.add(new JLabel("Search:"));
        controls.add(new JTextField(10));
        controls.add(new JButton("Refresh"));
        controls.setBorder(new TitledBorder("Filters"));
        cp.add("Center", controls);

        JFrame frame = new JFrame();
        frame.setLayout(new BorderLayout());

        // Put the "Controls" first
        frame.add("North", cp);

        // Then the tree - we assume the Controls would somehow filter the tree
        JScrollPane scroll = new JScrollPane(new JTree());
        frame.add("Center", scroll);

        // Show/hide the "Controls"
        JButton toggle = new JButton(cp.getActionMap().get(
                JXCollapsiblePane.TOGGLE_ACTION));
        toggle.setText("Show/Hide Search Panel");
        frame.add("South", toggle);

        frame.pack();
        frame.setVisible(true);

    }

    public void openPage() throws IOException {
        String url = "http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.HomePageServlet_Alt?ui_lang_code=54";
        String url2 = "http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.WhereUsedSearchServlet?";
        
        HttpPost post = new HttpPost(url);
        List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();
        //ValuePairs.add(new BasicNameValuePair("partNo", txt_codigo.getText()));
        post.setEntity(new UrlEncodedFormEntity(nameValuePairs, Consts.UTF_8));
        getDesktop().browse(post.getURI());
        
    }

    public void acessaSiteJD() {
        try {
            try {
                String caminho = "http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.HomePageServlet_Alt?ui_lang_code=54";
                URI site = new URI(caminho);
                URI site2 = new URI("http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.WhereUsedSearchServlet?partNo='RE255'");
                //getDesktop().browse((URI)site);
                getDesktop().browse((URI) site2);
            } catch (IOException ex) {
                Logger.getLogger(teste.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(teste.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   

}
